
package uy.gub.imm.sae.business.ws.guiatramites;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GuiaTramitesSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GuiaTramitesSoap {


    /**
     * 
     * @param entrada
     * @return
     *     returns org.tempuri.ObtTramitesMasConsultadosResponseType
     */
    @WebMethod(action = "http://tempuri.org/obtTramitesMasConsultados")
    @WebResult(name = "obtTramitesMasConsultadosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtTramitesMasConsultados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitesMasConsultados")
    @ResponseWrapper(localName = "obtTramitesMasConsultadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitesMasConsultadosResponse")
    public ObtTramitesMasConsultadosResponseType obtTramitesMasConsultados(
        @WebParam(name = "entrada", targetNamespace = "http://tempuri.org/")
        ObtTramitesMasConsultadosType entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns org.tempuri.ObtTramitesDestacadosResponseType
     */
    @WebMethod(action = "http://tempuri.org/obtTramitesDestacados")
    @WebResult(name = "obtTramitesDestacadosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtTramitesDestacados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitesDestacados")
    @ResponseWrapper(localName = "obtTramitesDestacadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitesDestacadosResponse")
    public ObtTramitesDestacadosResponseType obtTramitesDestacados(
        @WebParam(name = "entrada", targetNamespace = "http://tempuri.org/")
        ObtTramitesDestacadosType entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns org.tempuri.ObtTramitesEnOrdenAlfabeticoResponseType
     */
    @WebMethod(action = "http://tempuri.org/obtTramitesEnOrdenAlfabetico")
    @WebResult(name = "obtTramitesEnOrdenAlfabeticoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtTramitesEnOrdenAlfabetico", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitesEnOrdenAlfabetico")
    @ResponseWrapper(localName = "obtTramitesEnOrdenAlfabeticoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitesEnOrdenAlfabeticoResponse")
    public ObtTramitesEnOrdenAlfabeticoResponseType obtTramitesEnOrdenAlfabetico(
        @WebParam(name = "entrada", targetNamespace = "http://tempuri.org/")
        ObtTramitesEnOrdenAlfabeticoType entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns org.tempuri.ObtTramitesEnOrdenAlfabeticoResponseType
     */
    @WebMethod(action = "http://tempuri.org/obtTramitesPorOrgEnOrdenAlfabetico")
    @WebResult(name = "obtTramitesPorOrgEnOrdenAlfabeticoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtTramitesPorOrgEnOrdenAlfabetico", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitesPorOrgEnOrdenAlfabetico")
    @ResponseWrapper(localName = "obtTramitesPorOrgEnOrdenAlfabeticoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitesPorOrgEnOrdenAlfabeticoResponse")
    public ObtTramitesEnOrdenAlfabeticoResponseType obtTramitesPorOrgEnOrdenAlfabetico(
        @WebParam(name = "entrada", targetNamespace = "http://tempuri.org/")
        ObtTramitesPorOrgEnOrdenAlfabeticoType entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns org.tempuri.ObtTramitesPorIdResponse
     */
    @WebMethod(action = "http://tempuri.org/obtTramitePorId")
    @WebResult(name = "obtTramitePorIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtTramitePorId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitePorId")
    @ResponseWrapper(localName = "obtTramitePorIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitePorIdResponse")
    public ObtTramitesPorIdResponse obtTramitePorId(
        @WebParam(name = "entrada", targetNamespace = "http://tempuri.org/")
        ObtTramitesPorId entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns org.tempuri.ObtTramitesPorIdResponse
     */
    @WebMethod(action = "http://tempuri.org/obtTramitePorIdSinContarVisita")
    @WebResult(name = "obtTramitePorIdSinContarVisitaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtTramitePorIdSinContarVisita", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitePorIdSinContarVisita")
    @ResponseWrapper(localName = "obtTramitePorIdSinContarVisitaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtTramitePorIdSinContarVisitaResponse")
    public ObtTramitesPorIdResponse obtTramitePorIdSinContarVisita(
        @WebParam(name = "entrada", targetNamespace = "http://tempuri.org/")
        ObtTramitesPorId entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns org.tempuri.ObtArbolTemasResponseType
     */
    @WebMethod(action = "http://tempuri.org/obtArbolTemas")
    @WebResult(name = "obtArbolTemasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtArbolTemas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtArbolTemas")
    @ResponseWrapper(localName = "obtArbolTemasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtArbolTemasResponse")
    public ObtArbolTemasResponseType obtArbolTemas(
        @WebParam(name = "entrada", targetNamespace = "http://tempuri.org/")
        ObtArbolTemasType entrada);

    /**
     * 
     * @param pIdTramite
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/obtStatusPorIdTramite")
    @WebResult(name = "obtStatusPorIdTramiteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "obtStatusPorIdTramite", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtStatusPorIdTramite")
    @ResponseWrapper(localName = "obtStatusPorIdTramiteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtStatusPorIdTramiteResponse")
    public String obtStatusPorIdTramite(
        @WebParam(name = "pIdTramite", targetNamespace = "http://tempuri.org/")
        int pIdTramite);

}
