package uy.com.sofis.mrree.paltasolicitud;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-04T18:29:38.207-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "PAltaSolicitud", 
                  wsdlLocation = "file:./apaltasolicitud.wsdl",
                  targetNamespace = "TramitesExterior") 
public class PAltaSolicitud extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("TramitesExterior", "PAltaSolicitud");
    public final static QName PAltaSolicitudSoapPort = new QName("TramitesExterior", "PAltaSolicitudSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:./apaltasolicitud.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PAltaSolicitud.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:./apaltasolicitud.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PAltaSolicitud(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PAltaSolicitud(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PAltaSolicitud() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PAltaSolicitud(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PAltaSolicitud(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PAltaSolicitud(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PAltaSolicitudSoapPort
     */
    @WebEndpoint(name = "PAltaSolicitudSoapPort")
    public PAltaSolicitudSoapPort getPAltaSolicitudSoapPort() {
        return super.getPort(PAltaSolicitudSoapPort, PAltaSolicitudSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PAltaSolicitudSoapPort
     */
    @WebEndpoint(name = "PAltaSolicitudSoapPort")
    public PAltaSolicitudSoapPort getPAltaSolicitudSoapPort(WebServiceFeature... features) {
        return super.getPort(PAltaSolicitudSoapPort, PAltaSolicitudSoapPort.class, features);
    }

}
