
package uy.gub.imm.sae.common.factories.ws.client.recursos;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import uy.gub.imm.sae.entity.AgrupacionDato;
import uy.gub.imm.sae.entity.DatoDelRecurso;
import uy.gub.imm.sae.entity.Recurso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RecursosWS", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/")
public interface RecursosWS {


    /**
     * 
     * @param recurso
     * @return
     *     returns java.util.List<uy.gub.imm.sae.common.factories.ws.client.recursos.DatoDelRecurso>
     * @throws ApplicationException_Exception
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(name = "consultarDatosDelRecursoResult", targetNamespace = "")
    @RequestWrapper(localName = "consultarDatosDelRecurso", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.recursos.ConsultarDatosDelRecurso")
    @ResponseWrapper(localName = "consultarDatosDelRecursoResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.recursos.ConsultarDatosDelRecursoResponse")
    public List<DatoDelRecurso> consultarDatosDelRecurso(
        @WebParam(name = "recurso", targetNamespace = "")
        Recurso recurso)
        throws ApplicationException_Exception, BusinessException_Exception
    ;

    /**
     * 
     * @param recurso
     * @return
     *     returns java.util.List<uy.gub.imm.sae.common.factories.ws.client.recursos.AgrupacionDato>
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "consultarDefinicionDeCampos", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.recursos.ConsultarDefinicionDeCampos")
    @ResponseWrapper(localName = "consultarDefinicionDeCamposResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.recursos.ConsultarDefinicionDeCamposResponse")
    public List<AgrupacionDato> consultarDefinicionDeCampos(
        @WebParam(name = "recurso", targetNamespace = "")
        Recurso recurso)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "pingResult", targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.recursos.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.recursos.PingResponse")
    public String ping();

}
