
package uy.gub.imm.sae.business.ws.wstramite;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsTramite", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8080/SAE-StubsServiciosWebAgesic/wsTramite?wsdl")
public class WsTramite
    extends Service
{

    private final static QName WSTRAMITE_QNAME = new QName("http://tempuri.org/", "wsTramite");

    public WsTramite(URL wsdlLocation) {
        super(wsdlLocation, WSTRAMITE_QNAME);
    }

    /**
     * 
     * @return
     *     returns WsTramiteSoap
     */
    @WebEndpoint(name = "wsTramiteSoap")
    public WsTramiteSoap getWsTramiteSoap() {
        return super.getPort(new QName("http://tempuri.org/", "wsTramiteSoap"), WsTramiteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsTramiteSoap
     */
    @WebEndpoint(name = "wsTramiteSoap")
    public WsTramiteSoap getWsTramiteSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsTramiteSoap"), WsTramiteSoap.class, features);
    }

}
