
package uy.gub.imm.sae.business.ws.wstramite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsTramiteSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsTramiteSoap {


    /**
     * 
     * @param pOrg
     * @param pTramiteEstandar
     * @param pUE
     * @param pPassword
     * @param pUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AltaTramite", action = "http://tempuri.org/AltaTramite")
    @WebResult(name = "AltaTramiteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AltaTramite", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AltaTramite")
    @ResponseWrapper(localName = "AltaTramiteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AltaTramiteResponse")
    public String altaTramite(
        @WebParam(name = "pTramiteEstandar", targetNamespace = "http://tempuri.org/")
        byte[] pTramiteEstandar,
        @WebParam(name = "pUE", targetNamespace = "http://tempuri.org/")
        int pUE,
        @WebParam(name = "pOrg", targetNamespace = "http://tempuri.org/")
        int pOrg,
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pPassword", targetNamespace = "http://tempuri.org/")
        String pPassword);

    /**
     * 
     * @param pOrg
     * @param pTramiteEstandar
     * @param pUE
     * @param pPassword
     * @param pUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ModificarTramite", action = "http://tempuri.org/ModificarTramite")
    @WebResult(name = "ModificarTramiteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModificarTramite", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModificarTramite")
    @ResponseWrapper(localName = "ModificarTramiteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModificarTramiteResponse")
    public String modificarTramite(
        @WebParam(name = "pTramiteEstandar", targetNamespace = "http://tempuri.org/")
        byte[] pTramiteEstandar,
        @WebParam(name = "pUE", targetNamespace = "http://tempuri.org/")
        int pUE,
        @WebParam(name = "pOrg", targetNamespace = "http://tempuri.org/")
        int pOrg,
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pPassword", targetNamespace = "http://tempuri.org/")
        String pPassword);

    /**
     * 
     * @param pOrg
     * @param pUE
     * @param pIdTramite
     * @param pPassword
     * @param pUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BajaTramite", action = "http://tempuri.org/BajaTramite")
    @WebResult(name = "BajaTramiteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BajaTramite", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BajaTramite")
    @ResponseWrapper(localName = "BajaTramiteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BajaTramiteResponse")
    public String bajaTramite(
        @WebParam(name = "pIdTramite", targetNamespace = "http://tempuri.org/")
        int pIdTramite,
        @WebParam(name = "pUE", targetNamespace = "http://tempuri.org/")
        int pUE,
        @WebParam(name = "pOrg", targetNamespace = "http://tempuri.org/")
        int pOrg,
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pPassword", targetNamespace = "http://tempuri.org/")
        String pPassword);

    /**
     * 
     * @param pOrg
     * @param pUE
     * @param pPassword
     * @param pUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerCategorias", action = "http://tempuri.org/ObtenerCategorias")
    @WebResult(name = "ObtenerCategoriasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenerCategorias", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerCategorias")
    @ResponseWrapper(localName = "ObtenerCategoriasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerCategoriasResponse")
    public String obtenerCategorias(
        @WebParam(name = "pUE", targetNamespace = "http://tempuri.org/")
        int pUE,
        @WebParam(name = "pOrg", targetNamespace = "http://tempuri.org/")
        int pOrg,
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pPassword", targetNamespace = "http://tempuri.org/")
        String pPassword);

    /**
     * 
     * @param pPassword
     * @param pUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerUnidadesEjecutoras", action = "http://tempuri.org/ObtenerUnidadesEjecutoras")
    @WebResult(name = "ObtenerUnidadesEjecutorasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenerUnidadesEjecutoras", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerUnidadesEjecutoras")
    @ResponseWrapper(localName = "ObtenerUnidadesEjecutorasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerUnidadesEjecutorasResponse")
    public String obtenerUnidadesEjecutoras(
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pPassword", targetNamespace = "http://tempuri.org/")
        String pPassword);

    /**
     * 
     * @param pPassword
     * @param pUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerOrganismos", action = "http://tempuri.org/ObtenerOrganismos")
    @WebResult(name = "ObtenerOrganismosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenerOrganismos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerOrganismos")
    @ResponseWrapper(localName = "ObtenerOrganismosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerOrganismosResponse")
    public String obtenerOrganismos(
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pPassword", targetNamespace = "http://tempuri.org/")
        String pPassword);

    /**
     * 
     * @param pPassword
     * @param pUsuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ObtenerDepartamentos", action = "http://tempuri.org/ObtenerDepartamentos")
    @WebResult(name = "ObtenerDepartamentosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenerDepartamentos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerDepartamentos")
    @ResponseWrapper(localName = "ObtenerDepartamentosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenerDepartamentosResponse")
    public String obtenerDepartamentos(
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pPassword", targetNamespace = "http://tempuri.org/")
        String pPassword);

}
