
package uy.gub.agesic.itramites.bruto.web.ws.cabezal;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "cabezalService", targetNamespace = "http://ws.web.bruto.itramites.agesic.gub.uy/", wsdlLocation = "file:/home/spio/Desktop/Cosas/AGESIC-AGENDA/trazabilidad/v2/trazabilidad_v2_cabezal.wsdl")
public class CabezalService
    extends Service
{

    private final static QName CABEZALSERVICE_QNAME = new QName("http://ws.web.bruto.itramites.agesic.gub.uy/", "cabezalService");

    public CabezalService(URL wsdlLocation) {
        super(wsdlLocation, CABEZALSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns CabezalWS
     */
    @WebEndpoint(name = "CabezalWSPort")
    public CabezalWS getCabezalWSPort() {
        return super.getPort(new QName("http://ws.web.bruto.itramites.agesic.gub.uy/", "CabezalWSPort"), CabezalWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CabezalWS
     */
    @WebEndpoint(name = "CabezalWSPort")
    public CabezalWS getCabezalWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.web.bruto.itramites.agesic.gub.uy/", "CabezalWSPort"), CabezalWS.class, features);
    }

}
