
package uy.gub.agesic.itramites.bruto.web.ws.linea;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * La numeración de los enumerados está basada en el modelo de trazas definido por Unit
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LineaWS", targetNamespace = "http://ws.web.bruto.itramites.agesic.gub.uy/lineaService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LineaWS {


    /**
     * 
     * @param traza
     * @return
     *     returns uy.gub.agesic.itramites.bruto.web.ws.lineaservice.ResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "persist", targetNamespace = "http://ws.web.bruto.itramites.agesic.gub.uy/lineaService", className = "uy.gub.agesic.itramites.bruto.web.ws.lineaservice.Persist")
    @ResponseWrapper(localName = "persistResponse", targetNamespace = "http://ws.web.bruto.itramites.agesic.gub.uy/lineaService", className = "uy.gub.agesic.itramites.bruto.web.ws.lineaservice.PersistResponse")
    public ResponseDTO persist(
        @WebParam(name = "traza", targetNamespace = "")
        LineaDTO traza);

}
