package uy.com.sofis.mrree.pcancelarsolicitud;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-05T12:57:30.347-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "PCancelarSolicitud", 
                  wsdlLocation = "file:./apcancelarsolicitud.wsdl",
                  targetNamespace = "TramitesExterior") 
public class PCancelarSolicitud extends Service {

    public final static QName SERVICE = new QName("TramitesExterior", "PCancelarSolicitud");
    public final static QName PCancelarSolicitudSoapPort = new QName("TramitesExterior", "PCancelarSolicitudSoapPort");
    
    public PCancelarSolicitud() {
      super(PCancelarSolicitud.class.getResource("./apcancelarsolicitud.wsdl"), SERVICE);
    }
    
    /**
     *
     * @return
     *     returns PCancelarSolicitudSoapPort
     */
    @WebEndpoint(name = "PCancelarSolicitudSoapPort")
    public PCancelarSolicitudSoapPort getPCancelarSolicitudSoapPort() {
        return super.getPort(PCancelarSolicitudSoapPort, PCancelarSolicitudSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PCancelarSolicitudSoapPort
     */
    @WebEndpoint(name = "PCancelarSolicitudSoapPort")
    public PCancelarSolicitudSoapPort getPCancelarSolicitudSoapPort(WebServiceFeature... features) {
        return super.getPort(PCancelarSolicitudSoapPort, PCancelarSolicitudSoapPort.class, features);
    }

}
