
package uy.gub.agesic.itramites.bruto.web.ws.linea;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "lineaService", targetNamespace = "http://ws.web.bruto.itramites.agesic.gub.uy/lineaService", wsdlLocation = "file:/home/spio/Desktop/Cosas/AGESIC-AGENDA/trazabilidad/v2/trazabilidad_v2_linea.wsdl")
public class LineaService
    extends Service
{

    private final static QName LINEASERVICE_QNAME = new QName("http://ws.web.bruto.itramites.agesic.gub.uy/lineaService", "lineaService");

    public LineaService(URL wsdlLocation) {
        super(wsdlLocation, LINEASERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns LineaWS
     */
    @WebEndpoint(name = "LineaWSPort")
    public LineaWS getLineaWSPort() {
        return super.getPort(new QName("http://ws.web.bruto.itramites.agesic.gub.uy/lineaService", "LineaWSPort"), LineaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LineaWS
     */
    @WebEndpoint(name = "LineaWSPort")
    public LineaWS getLineaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.web.bruto.itramites.agesic.gub.uy/lineaService", "LineaWSPort"), LineaWS.class, features);
    }

}
