package uy.com.sofis.mrree.paltasolicitud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-04T18:29:38.202-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "TramitesExterior", name = "PAltaSolicitudSoapPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PAltaSolicitudSoapPort {

    @WebMethod(operationName = "Execute", action = "TramitesExterioraction/APALTASOLICITUD.Execute")
    @WebResult(name = "PAltaSolicitud.ExecuteResponse", targetNamespace = "TramitesExterior", partName = "parameters")
    public PAltaSolicitudExecuteResponse execute(
        @WebParam(partName = "parameters", name = "PAltaSolicitud.Execute", targetNamespace = "TramitesExterior")
        PAltaSolicitudExecute parameters
    );
}
