
package uy.com.sofis.sae.mrree.altasolicitud;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PAltaSolicitud", targetNamespace = "TramitesExterior")
public class PAltaSolicitud
    extends Service
{

    //private final static URL PALTASOLICITUD_WSDL_LOCATION;
    //private final static WebServiceException PALTASOLICITUD_EXCEPTION;
    private final static QName PALTASOLICITUD_QNAME = new QName("TramitesExterior", "PAltaSolicitud");

//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("file:/home/spio/Desarrollo/AGESIC-AGENDA2/MRREE/SAE-ServiciosMRREEStubs/wsdl/apaltasolicitud.wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        PALTASOLICITUD_WSDL_LOCATION = url;
//        PALTASOLICITUD_EXCEPTION = e;
//    }

    public PAltaSolicitud(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PAltaSolicitudSoapPort
     */
    @WebEndpoint(name = "PAltaSolicitudSoapPort")
    public PAltaSolicitudSoapPort getPAltaSolicitudSoapPort() {
        return super.getPort(new QName("TramitesExterior", "PAltaSolicitudSoapPort"), PAltaSolicitudSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PAltaSolicitudSoapPort
     */
    @WebEndpoint(name = "PAltaSolicitudSoapPort")
    public PAltaSolicitudSoapPort getPAltaSolicitudSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("TramitesExterior", "PAltaSolicitudSoapPort"), PAltaSolicitudSoapPort.class, features);
    }

//    private static URL __getWsdlLocation() {
//        if (PALTASOLICITUD_EXCEPTION!= null) {
//            throw PALTASOLICITUD_EXCEPTION;
//        }
//        return PALTASOLICITUD_WSDL_LOCATION;
//    }

}
