
package uy.com.sofis.sae.mrree.altasolicitud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PAltaSolicitudSoapPort", targetNamespace = "TramitesExterior")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PAltaSolicitudSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns uy.com.sofis.sae.mrree.altasolicitud.PAltaSolicitudExecuteResponse
     */
    @WebMethod(operationName = "Execute", action = "TramitesExterioraction/APALTASOLICITUD.Execute")
    @WebResult(name = "PAltaSolicitud.ExecuteResponse", targetNamespace = "TramitesExterior", partName = "parameters")
    public PAltaSolicitudExecuteResponse execute(
        @WebParam(name = "PAltaSolicitud.Execute", targetNamespace = "TramitesExterior", partName = "parameters")
        PAltaSolicitudExecute parameters);

}
