
package uy.gub.agesic.novedades;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NuevaNovedadService", targetNamespace = "http://servicios.pge.red.uy/SAENovedades/publicacion")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NuevaNovedadService {


    /**
     * 
     * @param novedad
     */
    @WebMethod
    public void nuevaNovedad(
        @WebParam(name = "publicar", targetNamespace = "http://novedades.sae.agesic.gub.uy/", partName = "novedad")
        Publicar novedad);

}
