package uy.com.sofis.mrree.paltasolicitud;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-04T18:29:38.207-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "PAltaSolicitud", targetNamespace = "TramitesExterior") 
public class PAltaSolicitud extends Service {

    public final static QName SERVICE = new QName("TramitesExterior", "PAltaSolicitud");
    public final static QName PAltaSolicitudSoapPort = new QName("TramitesExterior", "PAltaSolicitudSoapPort");

    public PAltaSolicitud() {
      super(PAltaSolicitud.class.getResource("./apaltasolicitud.wsdl"), SERVICE);
    }

    /**
     *
     * @return
     *     returns PAltaSolicitudSoapPort
     */
    @WebEndpoint(name = "PAltaSolicitudSoapPort")
    public PAltaSolicitudSoapPort getPAltaSolicitudSoapPort() {
        return super.getPort(PAltaSolicitudSoapPort, PAltaSolicitudSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PAltaSolicitudSoapPort
     */
    @WebEndpoint(name = "PAltaSolicitudSoapPort")
    public PAltaSolicitudSoapPort getPAltaSolicitudSoapPort(WebServiceFeature... features) {
        return super.getPort(PAltaSolicitudSoapPort, PAltaSolicitudSoapPort.class, features);
    }

}
