
package com.sofis.agesic.ursea.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
public interface ServiceSoap {


    /**
     * Da de Alta la reserva de audiencia en la Agenda.<br /><br /> PARAMETROS <br /> IdOficina: id de la Oficina .<br /> Fecha: fecha de la reserva Formato dd/mm/yyyy.<br /> TurnoHora: hora de la reserva Formato HH:MM.<br /> 
     *     Serie: <br /> NumeroCredencial:<br /> FechaNacimiento: El ingreso de este dato es obligatorio<br />  NombrePadre:<br />   NombreMadre: <br /> 
     *     TipoTramite: INS (inscripción), TRA (traslado), REN (renovación), REC (rectificación) <br />  PrimerApellido: :<br />  SegundoApellido :<br /> PrimerNombre:<br />  SegundoNombre:<br />  PruebaCiudadania:<br />  Cedula:
     * 
     * @param nombrePadre
     * @param pruebaCiudadania
     * @param fecha
     * @param numeroCredencial
     * @param turnoHora
     * @param fechaNacimiento
     * @param segundoApellido
     * @param primerNombre
     * @param serie
     * @param tipoTramite
     * @param nombreMadre
     * @param primerApellido
     * @param segundoNombre
     * @param idOficina
     * @param cedula
     * @return
     *     returns com.sofis.agesic.ursea.client.Reserva
     */
    @WebMethod(operationName = "GrabarReservaWeb", action = "http://tempuri.org/GrabarReservaWeb")
    @WebResult(name = "GrabarReservaWebResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GrabarReservaWeb", targetNamespace = "http://tempuri.org/", className = "com.sofis.agesic.ursea.client.GrabarReservaWeb")
    @ResponseWrapper(localName = "GrabarReservaWebResponse", targetNamespace = "http://tempuri.org/", className = "com.sofis.agesic.ursea.client.GrabarReservaWebResponse")
    public Reserva grabarReservaWeb(
        @WebParam(name = "IdOficina", targetNamespace = "http://tempuri.org/")
        int idOficina,
        @WebParam(name = "Fecha", targetNamespace = "http://tempuri.org/")
        String fecha,
        @WebParam(name = "TurnoHora", targetNamespace = "http://tempuri.org/")
        String turnoHora,
        @WebParam(name = "Serie", targetNamespace = "http://tempuri.org/")
        String serie,
        @WebParam(name = "NumeroCredencial", targetNamespace = "http://tempuri.org/")
        String numeroCredencial,
        @WebParam(name = "FechaNacimiento", targetNamespace = "http://tempuri.org/")
        String fechaNacimiento,
        @WebParam(name = "NombrePadre", targetNamespace = "http://tempuri.org/")
        String nombrePadre,
        @WebParam(name = "NombreMadre", targetNamespace = "http://tempuri.org/")
        String nombreMadre,
        @WebParam(name = "TipoTramite", targetNamespace = "http://tempuri.org/")
        String tipoTramite,
        @WebParam(name = "PrimerApellido", targetNamespace = "http://tempuri.org/")
        String primerApellido,
        @WebParam(name = "SegundoApellido", targetNamespace = "http://tempuri.org/")
        String segundoApellido,
        @WebParam(name = "PrimerNombre", targetNamespace = "http://tempuri.org/")
        String primerNombre,
        @WebParam(name = "SegundoNombre", targetNamespace = "http://tempuri.org/")
        String segundoNombre,
        @WebParam(name = "PruebaCiudadania", targetNamespace = "http://tempuri.org/")
        String pruebaCiudadania,
        @WebParam(name = "Cedula", targetNamespace = "http://tempuri.org/")
        String cedula);

    /**
     * Lista la  cantidad de lugares diponibles cada media hora para la Oficina y Fecha dada.
     * 
     * @param fecha
     * @param idOficina
     * @return
     *     returns com.sofis.agesic.ursea.client.Lugares
     */
    @WebMethod(operationName = "LugaresDisponibles", action = "http://tempuri.org/LugaresDisponibles")
    @WebResult(name = "LugaresDisponiblesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LugaresDisponibles", targetNamespace = "http://tempuri.org/", className = "com.sofis.agesic.ursea.client.LugaresDisponibles")
    @ResponseWrapper(localName = "LugaresDisponiblesResponse", targetNamespace = "http://tempuri.org/", className = "com.sofis.agesic.ursea.client.LugaresDisponiblesResponse")
    public Lugares lugaresDisponibles(
        @WebParam(name = "IdOficina", targetNamespace = "http://tempuri.org/")
        int idOficina,
        @WebParam(name = "Fecha", targetNamespace = "http://tempuri.org/")
        String fecha);

}
