
package uy.com.sofis.mrree.pcancelarsolicitud;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-05T12:57:30.301-03:00
 * Generated source version: 3.1.7
 * 
 */
public final class PCancelarSolicitudSoapPort_PCancelarSolicitudSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("TramitesExterior", "PCancelarSolicitud");

    private PCancelarSolicitudSoapPort_PCancelarSolicitudSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PCancelarSolicitud.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PCancelarSolicitud ss = new PCancelarSolicitud(wsdlURL, SERVICE_NAME);
        PCancelarSolicitudSoapPort port = ss.getPCancelarSolicitudSoapPort();  
        
        {
        System.out.println("Invoking execute...");
        uy.com.sofis.mrree.pcancelarsolicitud.PCancelarSolicitudExecute _execute_parameters = new uy.com.sofis.mrree.pcancelarsolicitud.PCancelarSolicitudExecute();
        _execute_parameters.setSolicitudnumero("Solicitudnumero-141626357");
        uy.com.sofis.mrree.pcancelarsolicitud.PCancelarSolicitudExecuteResponse _execute__return = port.execute(_execute_parameters);
        System.out.println("execute.result=" + _execute__return);


        }

        System.exit(0);
    }

}
