package uy.com.sofis.mrree.pcancelarsolicitud;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-05T12:57:30.347-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "PCancelarSolicitud", 
                  wsdlLocation = "file:./apcancelarsolicitud.wsdl",
                  targetNamespace = "TramitesExterior") 
public class PCancelarSolicitud extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("TramitesExterior", "PCancelarSolicitud");
    public final static QName PCancelarSolicitudSoapPort = new QName("TramitesExterior", "PCancelarSolicitudSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:./apcancelarsolicitud.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PCancelarSolicitud.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:./apcancelarsolicitud.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PCancelarSolicitud(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PCancelarSolicitud(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PCancelarSolicitud() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PCancelarSolicitud(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PCancelarSolicitud(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PCancelarSolicitud(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PCancelarSolicitudSoapPort
     */
    @WebEndpoint(name = "PCancelarSolicitudSoapPort")
    public PCancelarSolicitudSoapPort getPCancelarSolicitudSoapPort() {
        return super.getPort(PCancelarSolicitudSoapPort, PCancelarSolicitudSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PCancelarSolicitudSoapPort
     */
    @WebEndpoint(name = "PCancelarSolicitudSoapPort")
    public PCancelarSolicitudSoapPort getPCancelarSolicitudSoapPort(WebServiceFeature... features) {
        return super.getPort(PCancelarSolicitudSoapPort, PCancelarSolicitudSoapPort.class, features);
    }

}
