
package uy.gub.imm.sae.common.factories.ws.client.agendar;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "AccesoMultipleException", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/")
public class AccesoMultipleException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AccesoMultipleException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AccesoMultipleException_Exception(String message, AccesoMultipleException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AccesoMultipleException_Exception(String message, AccesoMultipleException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: uy.gub.imm.sae.common.factories.ws.client.agendar.AccesoMultipleException
     */
    public AccesoMultipleException getFaultInfo() {
        return faultInfo;
    }

}
