
package uy.gub.imm.sae.common.factories.ws.client.agendar;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import uy.gub.imm.sae.common.SAEProfile;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "AgendarReservasService", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", wsdlLocation = "/SAE-WS/AgendarReservas?wsdl")
public class AgendarReservasService
    extends Service
{

    private final static URL AGENDARRESERVASSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(uy.gub.imm.sae.common.factories.ws.client.agendar.AgendarReservasService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = uy.gub.imm.sae.common.factories.ws.client.agendar.AgendarReservasService.class.getResource(".");
            
            url = new URL(
            			baseUrl, 
            			SAEProfile.getInstance().getProperties().getProperty(SAEProfile.ENVIRONMENT_PROFILE_WS_WSDL_HOST) + 
            			"/" + SAEProfile.getInstance().getProperties().getProperty(SAEProfile.ENVIRONMENT_PROFILE_WS_WSDL_CONTEXT_ROOT) +
            			"/AgendarReservas?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '" + 
            				SAEProfile.getInstance().getProperties().getProperty(SAEProfile.ENVIRONMENT_PROFILE_WS_WSDL_HOST) + 
            				"/" + SAEProfile.getInstance().getProperties().getProperty(SAEProfile.ENVIRONMENT_PROFILE_WS_WSDL_CONTEXT_ROOT) + 
            				"/AgendarReservas?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AGENDARRESERVASSERVICE_WSDL_LOCATION = url;
    }

    public AgendarReservasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgendarReservasService() {
        super(AGENDARRESERVASSERVICE_WSDL_LOCATION, new QName("http://montevideo.gub.uy/schema/sae/1.0/", "AgendarReservasService"));
    }

    /**
     * 
     * @return
     *     returns AgendarReservasWS
     */
    @WebEndpoint(name = "AgendarReservasPort")
    public AgendarReservasWS getAgendarReservasPort() {
        return super.getPort(new QName("http://montevideo.gub.uy/schema/sae/1.0/", "AgendarReservasPort"), AgendarReservasWS.class);
    }

}
