
package uy.gub.imm.sae.common.factories.ws.client.agendar;

import java.util.HashMap;
import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import uy.gub.imm.sae.common.VentanaDeTiempo;
import uy.gub.imm.sae.entity.Agenda;
import uy.gub.imm.sae.entity.DatoASolicitar;
import uy.gub.imm.sae.entity.DatoReserva;
import uy.gub.imm.sae.entity.Disponibilidad;
import uy.gub.imm.sae.entity.Recurso;
import uy.gub.imm.sae.entity.Reserva;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AgendarReservasWS", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/")
public interface AgendarReservasWS {


    /**
     * 
     * @param reserva
     * @return
     *     returns uy.gub.imm.sae.common.factories.ws.client.agendar.Reserva
     * @throws ApplicationException_Exception
     * @throws AccesoMultipleException_Exception
     * @throws BusinessException_Exception
     * @throws ValidacionException_Exception
     * @throws ErrorValidacionException_Exception
     * @throws WarningValidacionCommitException_Exception
     * @throws WarningValidacionException_Exception
     * @throws ErrorValidacionCommitException_Exception
     * @throws UserException_Exception
     * @throws ValidacionClaveUnicaException_Exception
     * @throws ValidacionPorCampoException_Exception
     */
    @WebMethod
    @WebResult(name = "confirmarReservaResult", targetNamespace = "")
    @RequestWrapper(localName = "confirmarReserva", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConfirmarReserva")
    @ResponseWrapper(localName = "confirmarReservaResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConfirmarReservaResponse")
    public Reserva confirmarReserva(
        @WebParam(name = "reserva", targetNamespace = "")
        Reserva reserva)
        throws AccesoMultipleException_Exception, ApplicationException_Exception, BusinessException_Exception, ErrorValidacionCommitException_Exception, ErrorValidacionException_Exception, UserException_Exception, ValidacionClaveUnicaException_Exception, ValidacionException_Exception, ValidacionPorCampoException_Exception, WarningValidacionCommitException_Exception, WarningValidacionException_Exception
    ;

//    /**
//     * 
//     * @param nombre
//     * @return
//     *     returns uy.gub.imm.sae.common.factories.ws.client.agendar.Agenda
//     * @throws ApplicationException_Exception
//     * @throws BusinessException_Exception
//     */
//    @WebMethod
//    @WebResult(name = "consultarAgendaPorNombreResult", targetNamespace = "")
//    @RequestWrapper(localName = "consultarAgendaPorNombre", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConsultarAgendaPorNombre")
//    @ResponseWrapper(localName = "consultarAgendaPorNombreResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConsultarAgendaPorNombreResponse")
//    public Agenda consultarAgendaPorNombre(
//        @WebParam(name = "nombre", targetNamespace = "")
//        String nombre)
//        throws ApplicationException_Exception, BusinessException_Exception
//    ;

    /**
     * 
     * @param nombre
     * @return
     *     returns uy.gub.imm.sae.common.factories.ws.client.agendar.Agenda
     * @throws ApplicationException_Exception
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(name = "consultarAgendaPorIdResult", targetNamespace = "")
    @RequestWrapper(localName = "consultarAgendaPorId", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConsultarAgendaPorId")
    @ResponseWrapper(localName = "consultarAgendaPorIdResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConsultarAgendaPorIdResponse")
    public Agenda consultarAgendaPorId(
        @WebParam(name = "id", targetNamespace = "")
        Integer id)
        throws ApplicationException_Exception, BusinessException_Exception
    ;
    
    /**
     * 
     * @param agenda
     * @return
     *     returns java.util.List<uy.gub.imm.sae.common.factories.ws.client.agendar.Recurso>
     * @throws ApplicationException_Exception
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(name = "consultarRecursosResult", targetNamespace = "")
    @RequestWrapper(localName = "consultarRecursos", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConsultarRecursos")
    @ResponseWrapper(localName = "consultarRecursosResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConsultarRecursosResponse")
    public List<Recurso> consultarRecursos(
        @WebParam(name = "agenda", targetNamespace = "")
        Agenda agenda)
        throws ApplicationException_Exception, BusinessException_Exception
    ;

    /**
     * 
     * @param datos
     * @param recurso
     * @return
     *     returns uy.gub.imm.sae.common.factories.ws.client.agendar.Reserva
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(name = "consultarReservaPorDatosClaveResult", targetNamespace = "")
    @RequestWrapper(localName = "consultarReservaPorDatosClave", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConsultarReservaPorDatosClave")
    @ResponseWrapper(localName = "consultarReservaPorDatosClaveResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ConsultarReservaPorDatosClaveResponse")
    public Reserva consultarReservaPorDatosClave(
        @WebParam(name = "recurso", targetNamespace = "")
        Recurso recurso,
        @WebParam(name = "datos", targetNamespace = "")
        HashMap<DatoASolicitar, DatoReserva> datos)
        throws ApplicationException_Exception
    ;

    /**
     * 
     * @param reserva
     * @throws BusinessException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "desmarcarReserva", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.DesmarcarReserva")
    @ResponseWrapper(localName = "desmarcarReservaResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.DesmarcarReservaResponse")
    public void desmarcarReserva(
        @WebParam(name = "reserva", targetNamespace = "")
        Reserva reserva)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param disponibilidad
     * @return
     *     returns uy.gub.imm.sae.common.factories.ws.client.agendar.Reserva
     * @throws BusinessException_Exception
     * @throws UserException_Exception
     * @throws UserCommitException_Exception
     */
    @WebMethod
    @WebResult(name = "marcarReservaDisponibleResult", targetNamespace = "")
    @RequestWrapper(localName = "marcarReservaDisponible", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.MarcarReservaDisponible")
    @ResponseWrapper(localName = "marcarReservaDisponibleResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.MarcarReservaDisponibleResponse")
    public Reserva marcarReservaDisponible(
        @WebParam(name = "disponibilidad", targetNamespace = "")
        Disponibilidad disponibilidad)
        throws BusinessException_Exception, UserCommitException_Exception, UserException_Exception
    ;

    /**
     * 
     * @param ventanaDeTiempo
     * @param recurso
     * @return
     *     returns java.util.List<java.lang.Integer>
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(name = "obtenerCuposPorDiaResult", targetNamespace = "")
    @RequestWrapper(localName = "obtenerCuposPorDia", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ObtenerCuposPorDia")
    @ResponseWrapper(localName = "obtenerCuposPorDiaResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ObtenerCuposPorDiaResponse")
    public List<Integer> obtenerCuposPorDia(
        @WebParam(name = "recurso", targetNamespace = "")
        Recurso recurso,
        @WebParam(name = "ventanaDeTiempo", targetNamespace = "")
        VentanaDeTiempo ventanaDeTiempo)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param ventanaDeTiempo
     * @param recurso
     * @return
     *     returns java.util.List<uy.gub.imm.sae.common.factories.ws.client.agendar.Disponibilidad>
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(name = "obtenerDisponibilidadesResult", targetNamespace = "")
    @RequestWrapper(localName = "obtenerDisponibilidades", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ObtenerDisponibilidades")
    @ResponseWrapper(localName = "obtenerDisponibilidadesResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ObtenerDisponibilidadesResponse")
    public List<Disponibilidad> obtenerDisponibilidades(
        @WebParam(name = "recurso", targetNamespace = "")
        Recurso recurso,
        @WebParam(name = "ventanaDeTiempo", targetNamespace = "")
        VentanaDeTiempo ventanaDeTiempo)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param recurso
     * @return
     *     returns uy.gub.imm.sae.common.factories.ws.client.agendar.VentanaDeTiempo
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(name = "obtenerVentanaCalendarioInternetResult", targetNamespace = "")
    @RequestWrapper(localName = "obtenerVentanaCalendarioInternet", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ObtenerVentanaCalendarioInternet")
    @ResponseWrapper(localName = "obtenerVentanaCalendarioInternetResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.ObtenerVentanaCalendarioInternetResponse")
    public VentanaDeTiempo obtenerVentanaCalendarioInternet(
        @WebParam(name = "recurso", targetNamespace = "")
        Recurso recurso)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "pingResult", targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://montevideo.gub.uy/schema/sae/1.0/", className = "uy.gub.imm.sae.common.factories.ws.client.agendar.PingResponse")
    public String ping();

}
