
package uy.gub.imm.sae.business.ws.guiatramites;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GuiaTramites", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8080/SAE-StubsServiciosWebAgesic/GuiaTramites?wsdl")
public class GuiaTramites
    extends Service
{

    private final static QName GUIATRAMITES_QNAME = new QName("http://tempuri.org/", "GuiaTramites");

    public GuiaTramites(URL wsdlLocation) {
        super(wsdlLocation, GUIATRAMITES_QNAME);
    }

    /**
     * 
     * @return
     *     returns GuiaTramitesSoap
     */
    @WebEndpoint(name = "GuiaTramitesSoap")
    public GuiaTramitesSoap getGuiaTramitesSoap() {
        return super.getPort(new QName("http://tempuri.org/", "GuiaTramitesSoap"), GuiaTramitesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GuiaTramitesSoap
     */
    @WebEndpoint(name = "GuiaTramitesSoap")
    public GuiaTramitesSoap getGuiaTramitesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "GuiaTramitesSoap"), GuiaTramitesSoap.class, features);
    }

}
